// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6n3iW6LL7L2YS1z9QR_4lanRDNd7pRU',
    appId: '1:219432835653:web:42c23124b3a3990d28e12c',
    messagingSenderId: '219432835653',
    projectId: 'saltit-a6595',
    authDomain: 'saltit-a6595.firebaseapp.com',
    storageBucket: 'saltit-a6595.firebasestorage.app',
    measurementId: 'G-DEXGQQ8QS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn2AVFV5AwFDZ_jQzCTrtiZ5AO1y136Ls',
    appId: '1:219432835653:android:049d89e8234e7b9528e12c',
    messagingSenderId: '219432835653',
    projectId: 'saltit-a6595',
    storageBucket: 'saltit-a6595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGFSF4UUgaTNEa2SwLI4a0eZJ_HSBR-9g',
    appId: '1:219432835653:ios:640a4a5cbbd94f6c28e12c',
    messagingSenderId: '219432835653',
    projectId: 'saltit-a6595',
    storageBucket: 'saltit-a6595.firebasestorage.app',
    iosBundleId: 'com.example.flutterKasir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGFSF4UUgaTNEa2SwLI4a0eZJ_HSBR-9g',
    appId: '1:219432835653:ios:640a4a5cbbd94f6c28e12c',
    messagingSenderId: '219432835653',
    projectId: 'saltit-a6595',
    storageBucket: 'saltit-a6595.firebasestorage.app',
    iosBundleId: 'com.example.flutterKasir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_6n3iW6LL7L2YS1z9QR_4lanRDNd7pRU',
    appId: '1:219432835653:web:e48a0fd5aa495d5f28e12c',
    messagingSenderId: '219432835653',
    projectId: 'saltit-a6595',
    authDomain: 'saltit-a6595.firebaseapp.com',
    storageBucket: 'saltit-a6595.firebasestorage.app',
    measurementId: 'G-DY9M03G6X8',
  );
}
